"""Repository interfaces (protocols) for Family Financial OS.

Defines the contracts that infrastructure implementations must follow.
The application layer depends on these abstractions, not on SQLite.
"""

from __future__ import annotations
from typing import List, Optional, Dict, Any
from decimal import Decimal

from app.domain.domain import (
    Money, Timestamp, Account, AccountType, Transaction,
    TransactionType, TransactionStatus, Budget, Debt, Goal,
    Asset, Liability, Member, Household, User, Notification,
    LedgerEntry, RecurringPayment, DebtPayment, GoalContribution,
    Transfer, Session
)


class HouseholdRepository:
    def create(self, household: Household) -> Household: ...
    def get_by_id(self, id: str) -> Optional[Household]: ...
    def get_all(self) -> List[Household]: ...
    def update(self, household: Household) -> Household: ...
    def delete(self, id: str) -> None: ...


class MemberRepository:
    def create(self, member: Member) -> Member: ...
    def get_by_id(self, id: str) -> Optional[Member]: ...
    def get_by_household(self, household_id: str) -> List[Member]: ...
    def delete(self, id: str) -> None: ...


class AccountRepository:
    def create(self, account: Account) -> Account: ...
    def get_by_id(self, id: str) -> Optional[Account]: ...
    def get_by_household(self, household_id: str) -> List[Account]: ...
    def get_balance(self, account_id: str) -> Optional[Money]: ...
    def update_balance(self, id: str, balance: Money) -> None: ...
    def delete(self, id: str, household_id: str) -> None: ...


class CategoryRepository:
    def create(self, category: Category) -> Category: ...
    def get_by_id(self, id: str) -> Optional[Category]: ...
    def get_by_household(self, household_id: str) -> List[Category]: ...


class TransactionRepository:
    def create(self, transaction: Transaction) -> Transaction: ...
    def get_by_id(self, id: str) -> Optional[Transaction]: ...
    def get_by_household(self, household_id: str) -> List[Transaction]: ...
    def get_by_account(self, account_id: str) -> List[Transaction]: ...
    def get_by_date_range(self, household_id: str, start: str, end: str) -> List[Transaction]: ...
    def get_count(self, household_id: str) -> int: ...
    def update(self, transaction: Transaction) -> Transaction: ...
    def delete(self, id: str, household_id: str) -> None: ...


class TransferRepository:
    def create(self, transfer: Transfer) -> Transfer: ...
    def get_by_id(self, id: str) -> Optional[Transfer]: ...
    def get_by_household(self, household_id: str) -> List[Transfer]: ...
    def delete(self, id: str, household_id: str) -> None: ...


class LedgerEntryRepository:
    def create(self, entry: LedgerEntry) -> LedgerEntry: ...
    def get_by_account(self, account_id: str) -> List[LedgerEntry]: ...


class BudgetRepository:
    def create(self, budget: Budget) -> Budget: ...
    def get_by_id(self, id: str) -> Optional[Budget]: ...
    def get_by_household(self, household_id: str) -> List[Budget]: ...
    def update(self, id: str, updates: Dict[str, Any]) -> Budget: ...
    def delete(self, id: str, household_id: str) -> None: ...


class RecurringPaymentRepository:
    def create(self, payment: RecurringPayment) -> RecurringPayment: ...
    def get_by_id(self, id: str) -> Optional[RecurringPayment]: ...
    def get_by_household(self, household_id: str) -> List[RecurringPayment]: ...
    def update(self, id: str, updates: Dict[str, Any]) -> RecurringPayment: ...
    def delete(self, id: str, household_id: str) -> None: ...


class DebtRepository:
    def create(self, debt: Debt) -> Debt: ...
    def get_by_id(self, id: str) -> Optional[Debt]: ...
    def get_by_household(self, household_id: str) -> List[Debt]: ...
    def update(self, debt: Debt) -> Debt: ...
    def delete(self, id: str, household_id: str) -> None: ...


class DebtPaymentRepository:
    def create(self, payment: DebtPayment) -> DebtPayment: ...
    def get_by_debt(self, debt_id: str) -> List[DebtPayment]: ...


class GoalRepository:
    def create(self, goal: Goal) -> Goal: ...
    def get_by_id(self, id: str) -> Optional[Goal]: ...
    def get_by_household(self, household_id: str) -> List[Goal]: ...
    def update(self, id: str, updates: Dict[str, Any]) -> Goal: ...
    def delete(self, id: str, household_id: str) -> None: ...


class GoalContributionRepository:
    def create(self, contribution: GoalContribution) -> GoalContribution: ...
    def get_by_goal(self, goal_id: str) -> List[GoalContribution]: ...


class AssetRepository:
    def create(self, asset: Asset) -> Asset: ...
    def get_by_id(self, id: str) -> Optional[Asset]: ...
    def get_by_household(self, household_id: str) -> List[Asset]: ...
    def update(self, asset: Asset) -> Asset: ...
    def delete(self, id: str, household_id: str) -> None: ...


class LiabilityRepository:
    def create(self, liability: Liability) -> Liability: ...
    def get_by_id(self, id: str) -> Optional[Liability]: ...
    def get_by_household(self, household_id: str) -> List[Liability]: ...
    def update(self, liability: Liability) -> Liability: ...
    def delete(self, id: str, household_id: str) -> None: ...


class UserRepository:
    def create(self, user: User) -> User: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def get_by_id(self, id: str) -> Optional[User]: ...


class SessionRepository:
    def create(self, session: Session) -> Session: ...
    def get_by_id(self, session_id: str) -> Optional[Session]: ...
    def delete(self, session_id: str) -> None: ...


class NotificationRepository:
    def create(self, notification: Notification) -> Notification: ...
    def get_by_household(self, household_id: str) -> List[Notification]: ...
    def mark_as_read(self, id: str) -> None: ...
